AWSTemplateFormatVersion: 2010-09-09
Description: Create SecretsManager for GPSS Main
Parameters:
  GPSSCarrierBatchSize:
    Description: Specify Batch Size in Number
    Type: Number
    NoEcho: true
  TagValue:
    Description: Value for AppName Tag Key
    Default: Username
    Type: String
Resources:
  MySecretA:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Join 
        - ''
        - - GPSS_Main_Secrets-
          - !Sub '${AWS::StackName}'
      Description: This secret has a dynamically generated secret password.
      ReplicaRegions:
        - Region: us-west-2
      SecretString: !Join 
        - ''
        - - '{"GPSS_MAIN_POST_CARRIER_BATCH_SIZE":'
          - !Ref GPSSCarrierBatchSize
          - '}'
      Tags:
        - Key: AppName
          Value: !Ref TagValue
Outputs:
  SecretsName:
    Description: Creates Name
    Value: !Join 
      - ''
      - - GPSS_Main_Secrets-
        - !Sub '${AWS::StackName}'
